FROM plugins/base:multiarch@sha256:b7f7b4798e273cdb75281d30dfe61213b4b70f0f72cde2ae1c5dd38d0d780eb5

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-download /bin/
ENTRYPOINT [ "/bin/drone-download" ]
